# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-poetry"
	LogPath     = "/tmp/log/gf-poetry/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-poetry"
    Level       = "all"
    Stdout      = true

# Database.
[database]
    link  = "sqlite:./poetry.db"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-poetry/sql"
        Level  = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link  = "sqlite:./poetry.db"